[package]
name = "t-funk"
version = "0.1.0"
edition = "2021"
[features]

default = ["std"]
alloc = []
std = ["alloc"]

[dependencies]
typenum = "1.16.0"
t-funk-macros = { git = "https://github.com/bevy-rust-gpu/t-funk-macros" }
